apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-reliability-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-reliability-app
  template:
    metadata:
      labels:
        app: devops-reliability-app
    spec:
      containers:
        - name: app
          image: krishna7m1/devops-reliability-app:v1
          ports:
            - containerPort: 5000
          env:
            - name: ENV
              value: "production"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secret
                  key: dsn
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
